# Generated by Django 5.2.9 on 2025-12-03 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beschluss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('betrag', models.IntegerField()),
                ('beschluss_datum', models.DateField()),
                ('ablauf_datum', models.DateField()),
            ],
            options={
                'verbose_name': 'Beschluss',
                'verbose_name_plural': 'Beschlüsse',
            },
        ),
        migrations.CreateModel(
            name='Topf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('betrag', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Topf',
                'verbose_name_plural': 'Töpfe',
            },
        ),
        migrations.CreateModel(
            name='Ausgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('betrag', models.IntegerField()),
                ('datum', models.DateField()),
                ('beleg', models.FileField(blank=True, null=True, upload_to='belege/')),
                ('beschluss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanztool.beschluss')),
            ],
            options={
                'verbose_name': 'Ausgabe',
                'verbose_name_plural': 'Ausgaben',
            },
        ),
        migrations.CreateModel(
            name='Kostenstelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('betrag', models.IntegerField()),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('topf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanztool.topf')),
            ],
            options={
                'verbose_name': 'Kostenstelle',
                'verbose_name_plural': 'Kostenstellen',
            },
        ),
        migrations.AddField(
            model_name='beschluss',
            name='kostenstelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanztool.kostenstelle'),
        ),
    ]
