# Generated by Django 5.2.9 on 2025-12-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanztool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausgabe',
            name='kommentar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beschluss',
            name='abgeschlossen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beschluss',
            name='kommentar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
